### ISSUE TITLE
Host in private network does not detects new peers on internet

### ISSUE THREAD

**Issue by Arkotek** [maxogden/discovery-channel#5]
Hello,

When my dedicated servers are using discovery-channel and I launch on my home network the same software, my local software manage to connect successfully to the remote servers (via DHT).

But if I spin up a new dedicated server with discovery-channel, my local software does not detect it via DHT (but the other dedicated servers do).

Do you have any idea on how to fix this? Any work around?

Thank you for this great module,

**Comment by mafintosh** [comment]
are you just using the default options?

**Comment by Arkotek** [comment]
Yes default options,

Why do dht.lookup is called only once [here](https://github.com/maxogden/discovery-channel/blob/master/index.js#L122)?

If I put a dirty setInterval on dht.lookup, my local node re-connect successfully to the remote nodes,

Unfortunately this dirty fix throw this exception:

```
(node) warning: possible EventEmitter memory leak detected. 11 update listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at RPC.addListener (events.js:252:17)
    at RPC._closest (/home/shant/gridcontrol/gridcontrol/node_modules/k-rpc/index.js:201:15)
    at RPC.closest (/home/shant/gridcontrol/gridcontrol/node_modules/k-rpc/index.js:172:8)
    at DHT._closest (/home/shant/gridcontrol/gridcontrol/node_modules/bittorrent-dht/client.js:515:13)
    at DHT.lookup (/home/shant/gridcontrol/gridcontrol/node_modules/bittorrent-dht/client.js:310:8)
    at Timeout._repeat (/home/shant/gridcontrol/gridcontrol/node_modules/discovery-channel/index.js:128:16)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by Arkotek** [comment]
stacktrace updated, I forgot to add the line about the eventemitter memory leak

**Comment by Arkotek** [comment]
Without the dirty fix, the node has been detected but 11 minutes after :/
trying to find a way to reduce the discovery time

**Comment by Arkotek** [comment]
https://github.com/mafintosh/k-rpc/pull/3

**Comment by mafintosh** [comment]
the module reannounces to the dht every 10 min ish. this is by design and is similar to what other bt dht users do. you can set `{dht: {interval: someMilliseconds}}` to change this but beware that peers might ban  you if you are too aggresive.

**Comment by mafintosh** [comment]
to get more responsive usage try setting up a dns server using mafintosh/dns-discovery and pass the server name to the constructor
